INSERT INTO USER (PARTNER_ID, PWD, PARTNER_NAME, EMAIL, CREATED_DATE) VALUES ('band', '1234', '밴드', 'band@gmail.com', CURRENT_TIMESTAMP());
INSERT INTO USER (PARTNER_ID, PWD, PARTNER_NAME, EMAIL, CREATED_DATE) VALUES ('naver', '1234', '네이버', 'naver@gmail.com', CURRENT_TIMESTAMP());

INSERT INTO QUESTION (WRITER_ID, TITLE, CONTENTS, CREATED_DATE, COUNT_OF_ANSWER) VALUES(1, '국내에서 Ruby on Rails와 Play가', 'Ruby on Rails(이하 RoR)는', CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTION (WRITER_ID, TITLE, CONTENTS, CREATED_DATE, COUNT_OF_ANSWER) VALUES(2, '산지기가 쓴 글', '산지기는 군생활 때 나의 별명. 자바지기의 유래는 산지기', CURRENT_TIMESTAMP(), 0);